### PR TITLE
tests: Confirm installation of packages

### PR DESCRIPTION
**Pull request by dnaeon**
This one also fixes #20 tests

### CODE REVIEW

**Comment by raphink** [comment]
Right. Ideally though, we should be able to use the container infrastructure now that the Augeas PPAs are whitelisted.

**Comment by bastelfreak** [comment]
Hi @dnaeon, thanks for the PR! If I understand the `.travis.sh` got already fixed in the meantime so I will close this PR. Please ping us/reopen it if I understand the `.travis.sh` wrong.

**Comment by dhoppe** [comment]
@dnaeon Ping

**Comment by vinzent** [comment]
Acceptance are green with travis. seems this is not an issue anymore.

**Pull request closed without merging**
