### PR TITLE
Fixed puppetserver_gem confine using dynamic evaluation

### PR DESCRIPTION
**Pull request by elconas**
The current implementation of the confine, does not allow a 1-shot-puppetrun, as it reports Provider "puppetserver_gem" is not working as confine is evaluated only once and not dynamically. 

See https://tickets.puppetlabs.com/browse/PUP-5985 for details on confine evaluation.

### CODE REVIEW

**Comment by vinzent** [comment]
IMHO the module should depend on the puppetlabs/puppetserver_gem instead of having this inside this module.

**Comment by vinzent** [comment]
I even think theforeman/puppet is better suited to manage puppetserver and maintained than this module.

**Comment by vinzent** [comment]
Regarding puppetserver_gem see also #28

**Comment by elconas** [comment]
Question: from lookin at puppetlabs/puppetserver_gem, this seems to not support lazy evaluation. (e.g. allows puppetserver to install and install the gem's afterwerds in one single puppet run). Is that true ?

**Comment by vinzent** [comment]
why not just port your patch to https://github.com/puppetlabs/puppetlabs-puppetserver_gem/ so everyone has profit of it?

**Comment by elconas** [comment]
pfff ... let me try, but can't we fast forward here ? :) 
(would need a release soon)

**Comment by vinzent** [comment]
the puppetlabs/puppetserver_gem package provider has more options than this one. It seems like the puppetlabs/puppetserver_gem is a copy of this with more features.

I don't think its much work to port your patch to puppetlabs/puppetserver_gem .

**Comment by elconas** [comment]
Problem with puppetserver_gem is it only works with puppet 4.x

**Comment by vinzent** [comment]
is it really a problem? 

i've extended the acceptance test manifest ( https://github.com/voxpupuli/puppet-puppetserver/blob/master/spec/acceptance/puppetserver_spec.rb#L7 ) to be 

```
class { 'puppetserver': }
include ::puppetserver::hiera::eyaml
```
and ran it with 

```
BEAKER_debug=yes BEAKER_set="docker/ubuntu-16.04" PUPPET_INSTALL_TYPE="agent" be rake beaker
```

https://github.com/voxpupuli/puppet-puppetserver/blob/master/spec/acceptance/puppetserver_spec.rb#L11 should fail if the second run would have changed anything.

output of first run:

``` 
  Info: Loading facts
  Info: Loading facts
  Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
     (in /etc/puppetlabs/puppet/hiera.yaml)
  Warning: Undefined variable 'trusted.certname'; 
     (file & line not available)
  Notice: Compiled catalog for ubuntu-1604-x64.local in environment production in 0.14 seconds
  Info: Applying configuration version '1486064804'
  Notice: /Stage[main]/Puppetserver::Install/Package[puppetserver]/ensure: created
  Notice: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]/ensure: created
  Info: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]: Scheduling refresh of Class[Puppetserver::Service]
  Info: Class[Puppetserver::Service]: Scheduling refresh of Service[puppetserver]
  Notice: /Stage[main]/Puppetserver::Service/Service[puppetserver]/ensure: ensure changed 'stopped' to 'running'
  Info: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Unscheduling refresh on Service[puppetserver]
  Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
  Notice: Applied catalog in 131.23 seconds
```

is the problem maybe ordering of resources somehow?

**Comment by vinzent** [comment]
> Problem with puppetserver_gem is it only works with puppet 4.x

https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/

**Comment by elconas** [comment]
I tested this with 2.1.0

test.pp:
```
include puppetserver
include puppetserver::hiera::eyaml
```

Puppetrun (puppet4):
```
[root@server]# puppet apply test.pp --modulepath /opt/provision/modules/
Notice: Compiled catalog for server in environment production in 0.35 seconds
Notice: /Stage[main]/Puppetserver::Install/Package[puppetserver]/ensure: created
Error: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]: Provider puppetserver_gem is not functional on this host
Notice: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Dependency Package[hiera-eyaml] has failures: true
Warning: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Dependency Package[hiera-eyaml] has failures: true
Warning: /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Skipping because of failed dependencies
Notice: Applied catalog in 154.84 seconds
```

**Comment by vinzent** [comment]
i've tested on branch with #42  - this branch uses puppetlabs/puppetserver_gem instead of the included.

retested with master and indeed it fails. 

so with puppetlabs/puppetserver_gem it's not a problem. I would call this a strong reason to dump the included package provider.

**Comment by vinzent** [comment]
Travis shows green (https://travis-ci.org/voxpupuli/puppet-puppetserver/builds/197916287) including updated acceptance test with puppetlabs/pupetserver_gem and hiera eyaml on #42

**Comment by elconas** [comment]
https://github.com/voxpupuli/puppet-puppetserver/pull/42 fixes the same issue more persistenly, so dicarding this in favour of https://github.com/voxpupuli/puppet-puppetserver/pull/42

**Pull request closed without merging**
