### PR TITLE
Use puppetlabs/puppetserver_gem

### LINKED ISSUE #28: Depend on puppetlabs/puppetserver_gem instead of including it
It would likely be better to just depend on https://forge.puppet.com/puppetlabs/puppetserver_gem instead of vendoring it or shipping our own version of it.

### PR DESCRIPTION
**Pull request by vinzent**
Adds the dependency to metadata.json and removes the
provider.

As a side effect this allows idempotent runs when also puppetserver_gem packages are installed. This was not possible with the vendored in one.

Closes #28

### CODE REVIEW

**Comment by vinzent** [comment]
This PR conflicts with https://github.com/voxpupuli/puppet-puppetserver/pull/29

**Comment by vinzent** [comment]
updated acceptance test to check idempotency with a puppetserver gem included. works at least on my local docker. lets see whats going on with travis.

**Comment by elconas** [comment]
Hi, I ran this test with your code locally in this pull request: 

```
git fetch origin pull/42/head:28_use_puppetlabs_puppetserver_gem
git checkout 28_use_puppetlabs_puppetserver_gem
[root@server puppetserver]# git log --oneline
2f2827f FIXUP Use git:// URL instead in fixtures
ebca4cf Use puppetlabs/puppetserver_gem
167d91f Merge pull request #40 from vinzent/modulesync_0_19_3
fd5768a Add inline rubocop exceptions
...
```

Code:
```
class { 'puppetserver': }
include ::puppetserver::hiera::eyaml
```

Puppetrun:
```
[root@server puppetserver]# puppet apply /tmp/test.pp --modulepath /opt/provision/modules/
Notice: Compiled catalog for server in environment production in 0.36 seconds
Notice: /Stage[main]/Puppetserver::Install/Package[puppetserver]/ensure: created
Error: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]: Provider puppetserver_gem is not functional on this host
Notice: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Dependency Package[hiera-eyaml] has failures: true
Warning: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Dependency Package[hiera-eyaml] has failures: true
Warning: /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Skipping because of failed dependencies
Notice: Applied catalog in 140.55 seconds
```

Second run it works: 
```
[root@server puppetserver]# puppet apply /tmp/test.pp --modulepath /opt/provision/modules/
Notice: Compiled catalog for server in environment production in 0.38 seconds
Warning: Could not match io/console on JRuby shells out to stty for most operations

Warning: Could not match *** LOCAL GEMS ***

Warning: Could not match io/console on JRuby shells out to stty for most operations

Warning: Could not match *** LOCAL GEMS ***

Notice: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]/ensure: created
Notice: /Stage[main]/Puppetserver::Service/Service[puppetserver]/ensure: ensure changed 'stopped' to 'running'
Notice: Applied catalog in 82.46 seconds
```

**Comment by vinzent** [comment]
so whats your difference to the docker centos 6, centos 7 and debian 7 tests run by travis? Can you show your Pupppet version, facter version and what distro are you using?

**Comment by elconas** [comment]
It is PC1

```
[root@server puppetserver]# puppet -V
4.8.1
[root@server puppetserver]# facter -v
3.5.0 (commit 872c5707799c1c30925b632f20eab763ec03b5a4)
[root@server puppetserver]# hiera -v
3.2.2
```

**Comment by elconas** [comment]
My only idea: the acceptance test is not the first one (so puppetserver is already installed) - making the run a "second run", which works.

**Comment by vinzent** [comment]
acceptance tests run from a new system every time. no puppetserver preinstalled.

you can run the tests yourself (docker and internet access required):

```
BEAKER_debug=yes BEAKER_set="docker/centos-7" PUPPET_INSTALL_TYPE="agent" be rake beaker
```

or with 4.8.1:

```
PUPPET_AGENT_SUITE_VERSION=4.8.1 BEAKER_debug=yes BEAKER_set="docker/centos-7" PUPPET_INSTALL_TYPE="agent" be rake beaker
```

output of 4.8.1 for the first puppet run:

``` 
centos-7-x64 09:21:58$ puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.aTYOEV
  Info: Loading facts
  Info: Loading facts
  Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
     (in /etc/puppetlabs/puppet/hiera.yaml)
  Warning: Undefined variable 'trusted.certname'; 
     (file & line not available)
  Notice: Compiled catalog for centos-7-x64.local in environment production in 0.16 seconds
  Info: Applying configuration version '1486110123'
  Notice: /Stage[main]/Puppetserver::Install/Package[puppetserver]/ensure: created
  Notice: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]/ensure: created
  Info: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]: Scheduling refresh of Class[Puppetserver::Service]
  Info: Class[Puppetserver::Service]: Scheduling refresh of Service[puppetserver]
  Notice: /Stage[main]/Puppetserver::Service/Service[puppetserver]/ensure: ensure changed 'stopped' to 'running'
  Info: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Unscheduling refresh on Service[puppetserver]
  Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
  Notice: Applied catalog in 109.18 seconds
```

**Comment by vinzent** [comment]
forget about PUPPET_AGENT_INSTALL_SUITE seems it ignores it and installs latest (1.9 with Puppet 4.9.0) need to study docs about this param. :)

**Comment by vinzent** [comment]
ah its `PUPPET_INSTALL_VERSION=1.8.3` (version of puppet-agent package with Puppet 4.8)

**Comment by vinzent** [comment]
works also with vagrant+virtualbox and CentOS 7:

```
PUPPET_INSTALL_VERSION=1.8.3 BEAKER_debug=yes BEAKER_set="centos-72-x64" PUPPET_INSTALL_TYPE="agent" bundle exec rake beaker
``` 

nodeset requires a small addition because of 2g memory required by puppetserver by default:

```patch
diff --git a/spec/acceptance/nodesets/centos-72-x64.yml b/spec/acceptance/nodesets/centos-72-x64.yml
index 85af89d..297f35b 100644
--- a/spec/acceptance/nodesets/centos-72-x64.yml
+++ b/spec/acceptance/nodesets/centos-72-x64.yml
@@ -9,6 +9,7 @@ HOSTS:
     platform: el-7-x86_64
     box: puppetlabs/centos-7.2-64-nocm
     hypervisor: vagrant
+    vagrant_memsize: 3096
 CONFIG:
   type: foss
 ...

```

**Comment by elconas** [comment]
I tested with puppet aio 4.9.0 - same issue. 

````
[root@server]# puppet apply /tmp/muh.pp --modulepath /opt/provision/modules/
Warning: /etc/puppetlabs/code/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/code/hiera.yaml)
Warning: Undefined variable 'cluster';
   (file & line not available)
Warning: Undefined variable 'role';
   (file & line not available)
Warning: Undefined variable 'topic';
   (file & line not available)
Warning: Undefined variable 'location';
   (file & line not available)
Notice: Compiled catalog for server in environment production in 0.26 seconds
Notice: /Stage[main]/Puppetserver::Install/Package[puppetserver]/ensure: created
Error: /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]: Provider puppetserver_gem is not functional on this host
Notice: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Dependency Package[hiera-eyaml] has failures: true
Warning: /Stage[main]/Puppetserver::Service/Service[puppetserver]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Dependency Package[hiera-eyaml] has failures: true
Warning: /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Skipping because of failed dependencies
Notice: Applied catalog in 73.05 seconds
```

**Comment by elconas** [comment]
@vinzent Can you run a manual test ? 
(make sure puppetserver does not exist)

**Comment by vinzent** [comment]
> @vinzent <https://github.com/vinzent> Can you run a manual test ?
> (make sure puppetserver does not exist)
>

Puppetserver does not exist. the beaker test provisions a new system
every run.

I would not do anything other than the acceptance test: start a vagrant
virtualbox centos7, install puppet-agent, install dependent modules,
copy this module from source, run puppet apply.

If you come up with a beaker acceptance test that reproducible fails
with the idempotency problem (this means includes travis) I'll have a look.

**Comment by vinzent** [comment]
Am 03.02.2017 um 11:05 schrieb www.elconas.de:

> I tested with puppet aio 4.9.0 - same issue.
>
> |[root@server]# puppet apply /tmp/muh.pp --modulepath
> /opt/provision/modules/ ... Notice: Compiled catalog for server in
> environment production in 0.26 seconds Notice:
> /Stage[main]/Puppetserver::Install/Package[puppetserver]/ensure:
> created Error:
> /Stage[main]/Puppetserver::Hiera::Eyaml/Package[hiera-eyaml]: Provider
> puppetserver_gem is not functional on this host Notice:
> /Stage[main]/Puppetserver::Service/Service[puppetserver]: Dependency
> Package[hiera-eyaml] has failures: true Warning:
> /Stage[main]/Puppetserver::Service/Service[puppetserver]: Skipping
> because of failed dependencies Notice:
> /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Dependency
> Package[hiera-eyaml] has failures: true Warning:
> /Stage[main]/Puppetserver/Anchor[puppetserver::end]: Skipping because
> of failed dependencies Notice: Applied catalog in 73.05 seconds ``` |
are you shure the old package provider puppetserver_gem.rb is not lying
around somewhere in the module path (also basemodulepath)? this is the
only thing I can think of why this fails for you and works for beaker
acceptance tests.

**Comment by elconas** [comment]
https://github.com/puppetlabs/puppetlabs-puppetserver_gem does not even have any travis tests ... bad choice

**Comment by vinzent** [comment]
Am 03.02.2017 um 11:24 schrieb www.elconas.de:
>
> https://github.com/puppetlabs/puppetlabs-puppetserver_gem does not
> even have any travis tests ... bad choice
>
>

this repo has travis tests, but no spec tests for the package provider
and no acceptance tests for the package provider. So it's the very same.

beside the test I added here which shows that
puppetlabs/puppetserver_gem works idempotent with beaker acceptance tests.

**Comment by elconas** [comment]
@vinzent this was a nice tip. The provider was in a module.backup directory breaking everything. 

I can confirm that this code works in one run

```
package { 'puppetserver':
  ensure => present,
} ->
package { 'hiera-eyaml':
  ensure => present,
  provider => puppetserver_gem,
}
```

```
[root@server]# puppet apply /tmp/muh.pp --modulepath /opt/provision/modules/
Notice: Compiled catalog for server in environment production in 0.09 seconds
Notice: /Stage[main]/Main/Package[puppetserver]/ensure: created
Warning: Could not match io/console on JRuby shells out to stty for most operations

Warning: Could not match *** LOCAL GEMS ***

Notice: Applied catalog in 90.08 seconds
```

Gems:
```
[root@server]# /opt/puppetlabs/bin/puppetserver gem list

*** LOCAL GEMS ***

fast_gettext (1.1.0)
gettext (3.2.2)
gettext-setup (0.8)
hiera-eyaml (2.1.0)
highline (1.6.21)
hocon (1.1.3)
jar-dependencies (0.2.6)
jruby-openssl (0.9.16 java)
json (1.8.0 java)
locale (2.1.2)
rake (10.1.0)
rdoc (4.1.2)
semantic_puppet (0.1.3)
text (1.3.1)
trollop (2.1.2)
```
:+1:

**Comment by elconas** [comment]
Can you merge and release ? :)

**Comment by elconas** [comment]
One note: maybe you can add: 

to manifests/install.pp to force ordering

```
# Make sure that puppetserver is installed, prior to installing puppetserver gem's
# (otherwise the ressource collector does not work and we need multiple puppet runs)
Package <| title == 'puppetserver' |> -> Package <| provider == 'puppetserver_gem' |>
```

**Comment by vinzent** [comment]
> One note: maybe you can add:
>
> to manifests/install.pp to force ordering
>
> |# Make sure that puppetserver is installed, prior to installing
> puppetserver gem's # (otherwise the ressource collector does not work
> and we need multiple puppet runs) Package <| title == 'puppetserver'
> |> -> Package <| provider == 'puppetserver_gem' |> |
>
It seems to order correctly without this. Why adding it?

**Comment by elconas** [comment]
Could be accident ? Explicit vs implicit :)

**Comment by vinzent** [comment]
> Could be accident ? Explicit vs implicit :)

I think it waits until command https://github.com/puppetlabs/puppetlabs-puppetserver_gem/blob/master/lib/puppet/provider/package/puppetserver_gem.rb#L14 becomes available and runs before Service[puppetserver] because of dependency.

> A resource collector will always realize any virtual resources that match its search expression.

if somebody would use virtual resources all matching would be realized. this might be an undesired behaviour. A better approach would IMHO be to autorequire (which is a soft-dependency) the package in the puppetserver_gem provider (if this is  possible from providers).

**Comment by elconas** [comment]
Also ok, I can do dependencies on my side too... 
Release ??

**Comment by dhollinger** [comment]
Looks Good.

**Pull request merged**
