### PR TITLE
Added manage_service option

### PR DESCRIPTION
**Pull request by mvisonneau**

### CODE REVIEW

**Comment by alexjfisher** [comment]
@mvisonneau Hi!  Could you explain your motivation?

I'm not a fan of using `if !defined`.
Would a `manage_service` boolean parameter meet your needs?

**Comment by mvisonneau** [comment]
@alexjfisher, sure well my issue here is while I use it with the `puppetlabs/puppetdb` module onto the same host. This is what we have on the other module :

https://github.com/puppetlabs/puppetlabs-puppetdb/blob/master/manifests/master/config.pp#L169-L173
```puppet
if ! defined(Service[$puppet_service_name]) {
  service { $puppet_service_name:
    ensure => running,
  }
}
```

It causes a duplicate resources error if the puppetdb module is called first. In the meantime I would like to keep the ensure service running definition as part of the puppetserver as it makes more sense to me but sure, if you would rather like to have a manage_service option I'm fine with it, thanks :)

**Comment by bastelfreak** [comment]
Hi,
I talked to @alexjfisher on IRC about that. In our opinion there shouldn't be an `if ! defined()` around the service resource. In general I'm fine with this pattern but in this case the module is dedicated to manage puppetserver and unpredictable things can happen if another module takes over the responsibility to manage the service.

---

Is it possible for you to change/enforce the order your classes are parsed? Handling puppetserver before puppetdb should solve the issue?

**Comment by bastelfreak** [comment]
However I like the idea to manage the name of the service and I would merge that if you remove the `if ! defined()` and rename the commit.

**Comment by juniorsysadmin** [comment]
@mvisonneau bump

**Comment by mvisonneau** [comment]
let me know if this suits you well

**Comment by juniorsysadmin** [comment]
Tests are failing on master not due to this change. It would be great if there was a unit test for this PR, but if you're not able to do this, please create a tracking Issue for it.

**Comment by mvisonneau** [comment]
- Rebase done
- Spec tests created

**Comment by vinzent** [comment]
thank you @mvisonneau ! great to see rspec tests added.

**Pull request merged**
