### PR TITLE
Revert "Revert "modulesync 0.12.5"" or: Modulesync the second try!

### PR DESCRIPTION
**Pull request by bastelfreak**
Reverts voxpupuli/puppet-puppetserver#31

### CODE REVIEW

**Comment by bastelfreak** [comment]
We should go on here and fix the travis issues we have since the modulesync. Ping @bbriggs

**Comment by bbriggs** [comment]
Will be available to start the fixes in 10-15 min

-- Briggs

**Comment by juniorsysadmin** [comment]
@bbriggs @bastelfreak Roll forward and close this?

**Comment by vinzent** [comment]
obsolete

**Pull request closed without merging**
